### ISSUE TITLE
NPE on bad configuration

### ISSUE THREAD

**Issue by laullon** [wavefrontHQ/java#370]
https://github.com/wavefrontHQ/java/blob/ac619e175577aa1e8c0ad24e99ce3ef65f785d19/proxy/src/main/java/com/wavefront/agent/preprocessor/AgentPreprocessorConfiguration.java#L69

```
2019-03-18 10:34:35,541 WARN  [agent:loadListenerConfigurationFile] Loaded configuration file /var/vcap/jobs/wavefront_proxy/conf/wavefront.conf
2019-03-18 10:34:35,590 ERROR [agent:start] Aborting start-up
java.lang.NullPointerException: null
	at com.wavefront.agent.preprocessor.AgentPreprocessorConfiguration.loadFromStream(AgentPreprocessorConfiguration.java:69) ~[wavefront-proxy.jar:?]
	at com.wavefront.agent.AbstractAgent.initPreprocessors(AbstractAgent.java:849) ~[wavefront-proxy.jar:?]
	at com.wavefront.agent.AbstractAgent.loadListenerConfigurationFile(AbstractAgent.java:1107) ~[wavefront-proxy.jar:?]
	at com.wavefront.agent.AbstractAgent.start(AbstractAgent.java:1180) [wavefront-proxy.jar:?]
	at com.wavefront.agent.PushAgentDaemon.start(PushAgentDaemon.java:23) [wavefront-proxy.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
```

**Comment by vikramraman** [comment]
Closing as this has been addressed.
